### ISSUE TITLE
https://libraservice2.kulap.io fail on transfer and get balance

### ISSUE THREAD

**Issue by kenken64** [kulapio/libra-service#28]
500 internal error

**Comment by kenken64** [comment]
ac.testnet.libra.or is down

**Comment by kenken64** [comment]
Error: 13 INTERNAL: Failed to parse server response
    at Object.exports.createStatusError (/Users/phangty/Projects/libra-service/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/phangty/Projects/libra-service/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/phangty/Projects/libra-service/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/phangty/Projects/libra-service/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/phangty/Projects/libra-service/node_modules/grpc/src/client_interceptors.js:845:24) {
  code: 13,
  metadata: undefined,
